(() => {
"use strict";
const $=id=>document.getElementById(id), enc=new TextEncoder();
const K={auth:"xcc.auth.v3",data:"xcc.data.v3",theme:"xcc.theme.v3"};
const DEF={salt:"eC1jb250cm9sLWNlbnRlci0yMDI2",iterations:250000,verifier:"JyPlpNAaxAopxlURaqI5m/d5PVrKQUFjkw7NHQgNeso="};
const S={results:[],trends:[],view:"home",data:{accounts:[],saved:[],prefs:{seedCount:8,minViews:0},xClientId:""}};
const titles={home:["نظرة عامة","لوحة خاصة لإدارة الاكتشاف والنشر اليدوي"],discover:["اكتشاف التغريدات","بحث وترتيب حسب الزمن واللغة والتفاعل"],accounts:["حسابات X","اختصارات للحسابات التي تديرها"],compose:["النشر والرد","يفتح X الرسمي لإتمام النشر يدويًا"],saved:["المحفوظات","العناصر المحفوظة"],settings:["الإعدادات","الأمان وخيارات الاكتشاف"]};
const cat={general:"",news:"news breaking عاجل أخبار",tech:"technology AI software تقنية ذكاء اصطناعي",sports:"sports football soccer رياضة كرة",business:"business markets economy اقتصاد أسواق",crypto:"crypto bitcoin ethereum كريبتو",entertainment:"entertainment movies music ترفيه",science:"science space research علوم فضاء"};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const fmt=n=>{n=Number(n||0);return n>=1e6?(n/1e6).toFixed(1)+"M":n>=1e3?(n/1e3).toFixed(1)+"K":String(n)};
function toast(m){const e=$("toast");e.textContent=m;e.classList.remove("hidden");setTimeout(()=>e.classList.add("hidden"),3500)}
function cfg(){try{return JSON.parse(localStorage.getItem(K.auth))||DEF}catch{return DEF}}
async function verifier(pass,salt,it){const raw=Uint8Array.from(atob(salt),c=>c.charCodeAt(0));const k=await crypto.subtle.importKey("raw",enc.encode(pass),"PBKDF2",false,["deriveBits"]);const bits=await crypto.subtle.deriveBits({name:"PBKDF2",salt:raw,iterations:it,hash:"SHA-256"},k,256);return btoa(String.fromCharCode(...new Uint8Array(bits)))}
function load(){try{S.data=JSON.parse(localStorage.getItem(K.data))||S.data}catch{}}
function save(){localStorage.setItem(K.data,JSON.stringify(S.data));renderAll()}
async function login(){const c=cfg(),v=await verifier($("password").value,c.salt,c.iterations);if(v!==c.verifier){$("loginError").textContent="كلمة المرور غير صحيحة.";return}load();$("lock").classList.add("hidden");$("app").classList.remove("hidden");$("loginError").textContent="";renderAll();checkHealth(false)}
function logout(){$("password").value="";$("app").classList.add("hidden");$("lock").classList.remove("hidden")}
function setView(v){S.view=v;document.querySelectorAll(".view").forEach(x=>x.classList.add("hidden"));$("view-"+v).classList.remove("hidden");document.querySelectorAll("[data-view]").forEach(b=>b.classList.toggle("active",b.dataset.view===v));$("title").textContent=titles[v][0];$("subtitle").textContent=titles[v][1]}
async function fx(path,params={}){const u=new URL("https://api.fxtwitter.com"+path);Object.entries(params).forEach(([k,v])=>u.searchParams.set(k,v));const r=await fetch(u);let d={};try{d=await r.json()}catch{}if(!r.ok&&r.status!==404)throw new Error("HTTP "+r.status);return d}
async function checkHealth(show=true){try{const d=await fx("/2/trends",{type:"trending",count:5}),ok=Array.isArray(d.trends);$("sourceDot").className="dot "+(ok?"ok":"bad");$("sourceState").textContent=ok?"FxTwitter متصل":"المصدر غير متاح";$("kSource").textContent=ok?"متصل":"متعذر";$("healthBox").textContent=ok?"FxTwitter متصل ويستجيب. النشر يتم عبر نافذة X الرسمية.":"المصدر غير متاح حاليًا.";if(show)toast(ok?"المصدر يعمل.":"المصدر غير متاح.")}catch(e){$("sourceDot").className="dot bad";$("sourceState").textContent="تعذر الاتصال";$("kSource").textContent="متعذر";if(show)toast("تعذر فحص المصدر.")}}
async function loadTrends(){const box=$("trendBox");box.innerHTML='<span class="muted">جار التحميل...</span>';try{const d=await fx("/2/trends",{type:"trending",count:30});S.trends=d.trends||[];box.innerHTML=S.trends.slice(0,20).map((t,i)=>'<button class="trend" data-trend="'+esc(t.name||t.query||"")+'">'+(i+1)+". "+esc(t.name||t.query||"")+"</button>").join("");box.querySelectorAll("[data-trend]").forEach(b=>b.onclick=()=>{$("query").value=b.dataset.trend;setView("discover");runSearch()})}catch(e){box.innerHTML='<span class="error">تعذر تحميل الترندات.</span>'}}
function langOK(t,l){if(l==="all")return true;if(t.lang)return String(t.lang).toLowerCase()===l;const x=t.text||"";if(l==="ar")return /[\u0600-\u06ff]/.test(x);if(l==="tr")return /[çğıöşüÇĞİÖŞÜ]/.test(x);return /[A-Za-z]/.test(x)}
const views=t=>Number(t.views??t.view_count??0), score=t=>views(t)*.015+Number(t.likes||0)*2+Number(t.reposts||0)*3+Number(t.replies||0)*1.5+Number(t.quotes||0)*2.5;
function ago(ts){if(!ts)return"";const s=Math.max(0,Date.now()/1000-Number(ts));return s<3600?Math.floor(s/60)+" د":s<86400?Math.floor(s/3600)+" س":Math.floor(s/86400)+" ي"}
async function runSearch(){const hrs=Number($("hours").value),l=$("lang").value,sort=$("sort").value,limit=Number($("count").value),cut=Date.now()/1000-hrs*3600;let rows=[];$("results").className="tweets";$("results").innerHTML='<div class="empty">جار جلب النتائج...</div>';try{const typed=$("query").value.trim(),q=typed||cat[$("category").value]||"";if(q){const d=await fx("/2/search",{q,feed:sort==="recent"?"latest":"top",count:100});rows=d.results||[]}else{if(!S.trends.length){const d=await fx("/2/trends",{type:"trending",count:15});S.trends=d.trends||[]}const seeds=S.trends.slice(0,Number(S.data.prefs.seedCount||8));const ps=await Promise.allSettled(seeds.map(x=>fx("/2/search",{q:x.name||x.query,feed:"top",count:30})));ps.forEach(p=>{if(p.status==="fulfilled")rows.push(...(p.value.results||[]))})}const m=new Map();rows.forEach(t=>t&&t.id&&!m.has(String(t.id))&&m.set(String(t.id),t));rows=[...m.values()].filter(t=>Number(t.created_timestamp||0)>=cut).filter(t=>langOK(t,l)).filter(t=>views(t)>=Number(S.data.prefs.minViews||0));const cmp={views:(a,b)=>views(b)-views(a),engagement:(a,b)=>score(b)-score(a),likes:(a,b)=>Number(b.likes||0)-Number(a.likes||0),reposts:(a,b)=>Number(b.reposts||0)-Number(a.reposts||0),recent:(a,b)=>Number(b.created_timestamp||0)-Number(a.created_timestamp||0)}[sort];rows.sort(cmp);S.results=rows.slice(0,limit);$("searchMeta").textContent="تمت معالجة "+m.size+" نتيجة، وبعد الفلاتر بقي "+rows.length+".";renderResults();renderHome();renderAll()}catch(e){$("results").innerHTML='<div class="empty error">تعذر إكمال البحث.</div>'}}
function card(t,i,saved=false){const a=t.author||{},img=a.avatar_url?'<img class="avatar" src="'+esc(a.avatar_url)+'">':'<div class="avatar-fallback">'+esc((a.name||"?")[0])+"</div>";return '<article class="tweet"><div class="tweet-head"><div class="user">'+img+'<div><div class="name">'+esc(a.name||"مستخدم X")+'</div><div class="handle">@'+esc(a.screen_name||a.username||"unknown")+" · "+ago(t.created_timestamp)+'</div></div></div><div class="rank">'+(i+1)+'</div></div><div class="tweet-text">'+esc(t.text||"")+'</div><div class="metrics"><span>مشاهدات '+fmt(views(t))+'</span><span>إعجاب '+fmt(t.likes)+'</span><span>إعادة نشر '+fmt(t.reposts)+'</span><span>ردود '+fmt(t.replies)+'</span></div><div class="tweet-actions"><button class="secondary" data-a="reply" data-id="'+esc(t.id)+'">رد</button><button class="ghost" data-a="open" data-url="'+esc(t.url||("https://x.com/i/status/"+t.id))+'">فتح</button><button class="'+(saved?"danger":"ghost")+'" data-a="'+(saved?"unsave":"save")+'" data-id="'+esc(t.id)+'">'+(saved?"إزالة":"حفظ")+"</button></div></article>"}
function bindCards(box,rows){box.querySelectorAll("[data-a]").forEach(b=>b.onclick=()=>{if(b.dataset.a==="open")return window.open(b.dataset.url,"_blank","noopener");const t=rows.find(x=>String(x.id)===String(b.dataset.id));if(b.dataset.a==="reply"&&t){setView("compose");$("replyTarget").value=t.url||("https://x.com/i/status/"+t.id);$("replyText").focus()}if(b.dataset.a==="save"&&t&&!S.data.saved.some(x=>String(x.id)===String(t.id))){S.data.saved.unshift(t);S.data.saved=S.data.saved.slice(0,200);save();toast("تم الحفظ.")}if(b.dataset.a==="unsave"){S.data.saved=S.data.saved.filter(x=>String(x.id)!==String(b.dataset.id));save()}})}
function renderResults(){const b=$("results");if(!S.results.length){b.className="tweets empty";b.textContent="لا توجد نتائج مطابقة.";return}b.className="tweets";b.innerHTML=S.results.map((t,i)=>card(t,i)).join("");bindCards(b,S.results)}
function renderHome(){const b=$("homeResults"),r=S.results.slice(0,5);if(!r.length){b.className="tweets empty";b.textContent="لم يتم تشغيل بحث بعد.";return}b.className="tweets";b.innerHTML=r.map((t,i)=>card(t,i)).join("");bindCards(b,r)}
function renderSaved(){const b=$("savedList"),r=S.data.saved||[];if(!r.length){b.className="tweets empty";b.textContent="لا توجد عناصر محفوظة.";return}b.className="tweets";b.innerHTML=r.map((t,i)=>card(t,i,true)).join("");bindCards(b,r)}
function renderAccounts(){const b=$("accountList"),r=S.data.accounts||[];if(!r.length){b.className="stack empty";b.innerHTML='لا توجد حسابات مضافة. <button id="addHandle" class="secondary" style="margin-top:10px">إضافة حساب</button>';const x=$("addHandle");if(x)x.onclick=addAccount;return}b.className="stack";b.innerHTML=r.map((a,i)=>'<div class="account"><div><strong>@'+esc(a.handle)+'</strong><small>اختصار إدارة رقم '+(i+1)+'</small></div><div class="actions"><button class="secondary" data-use="'+esc(a.handle)+'">فتح الحساب</button><button class="danger" data-del="'+i+'">إزالة</button></div></div>').join("")+'<button id="addHandle" class="secondary">إضافة حساب آخر</button>';b.querySelectorAll("[data-use]").forEach(x=>x.onclick=()=>window.open("https://x.com/"+encodeURIComponent(x.dataset.use),"_blank","noopener"));b.querySelectorAll("[data-del]").forEach(x=>x.onclick=()=>{S.data.accounts.splice(Number(x.dataset.del),1);save()});$("addHandle").onclick=addAccount}
function addAccount(){let h=prompt("أدخل اسم الحساب بدون @");if(!h)return;h=h.trim().replace(/^@/,"");if(h&&!S.data.accounts.some(x=>x.handle.toLowerCase()===h.toLowerCase())){S.data.accounts.push({handle:h});save()}}
function renderAll(){$("kAccounts").textContent=S.data.accounts.length;$("kSaved").textContent=S.data.saved.length;$("kResults").textContent=S.results.length;$("seedCount").value=S.data.prefs.seedCount||8;$("minViews").value=S.data.prefs.minViews||0;$("clientId").value=S.data.xClientId||"";$("callback").value=location.origin+location.pathname;renderAccounts();renderSaved();renderHome()}
function intent(text,id=""){const u=new URL("https://twitter.com/intent/tweet");u.searchParams.set("text",text||"");if(id)u.searchParams.set("in_reply_to",id);window.open(u,"_blank","noopener")}
function tweetId(v){const m=String(v||"").match(/status\/(\d+)/);return m?m[1]:(/^\d+$/.test(String(v||"").trim())?String(v).trim():"")}
async function changePass(){const c=cfg(),old=await verifier($("oldPass").value,c.salt,c.iterations);if(old!==c.verifier)return toast("كلمة المرور الحالية غير صحيحة.");const n=$("newPass").value;if(n.length<12||n!==$("confirmPass").value)return toast("تحقق من كلمة المرور الجديدة وتأكيدها.");const salt=crypto.getRandomValues(new Uint8Array(18)),s=btoa(String.fromCharCode(...salt)),v=await verifier(n,s,250000);localStorage.setItem(K.auth,JSON.stringify({salt:s,iterations:250000,verifier:v}));$("oldPass").value=$("newPass").value=$("confirmPass").value="";toast("تم تغيير كلمة المرور لهذا المتصفح.")}
function bind(){
$("login").onclick=login;$("password").onkeydown=e=>e.key==="Enter"&&login();$("logout").onclick=logout;document.querySelectorAll("[data-view]").forEach(b=>b.onclick=()=>setView(b.dataset.view));document.querySelectorAll("[data-go]").forEach(b=>b.onclick=()=>setView(b.dataset.go));$("theme").onclick=()=>{const n=(document.documentElement.dataset.theme||"dark")==="dark"?"light":"dark";document.documentElement.dataset.theme=n;localStorage.setItem(K.theme,n)};$("refresh").onclick=()=>S.view==="discover"?runSearch():loadTrends();$("loadTrends").onclick=loadTrends;$("search").onclick=runSearch;$("trendSearch").onclick=async()=>{await loadTrends();$("query").value="";setView("discover");runSearch()};$("clearSearch").onclick=()=>{$("query").value="";S.results=[];renderResults();renderAll()};$("connectX").onclick=()=>{window.open("https://x.com/i/flow/login","_blank","noopener");toast("افتح حساب X ثم أضف اسم الحساب هنا كاختصار إدارة.");setTimeout(addAccount,700)};$("postText").oninput=()=>$("counter").textContent=$("postText").value.length+" / 280";$("publish").onclick=()=>intent($("postText").value);$("intentPost").onclick=()=>intent($("postText").value);$("reply").onclick=()=>{const id=tweetId($("replyTarget").value);if(!id)return toast("أدخل رابط تغريدة صالحًا.");intent($("replyText").value,id)};$("intentReply").onclick=$("reply").onclick;$("clearSaved").onclick=()=>{if(confirm("مسح المحفوظات؟")){S.data.saved=[];save()}};$("health").onclick=()=>checkHealth(true);$("savePrefs").onclick=()=>{S.data.prefs={seedCount:Math.max(3,Math.min(15,Number($("seedCount").value)||8)),minViews:Math.max(0,Number($("minViews").value)||0)};save();toast("تم حفظ الخيارات.")};$("saveOAuth").onclick=()=>{S.data.xClientId=$("clientId").value.trim();save();toast("تم حفظ Client ID محليًا؛ النسخة الحالية تستخدم نافذة X الرسمية للنشر.")};$("changePass").onclick=changePass}
document.documentElement.dataset.theme=localStorage.getItem(K.theme)||"dark";bind();
})();